In [1]:
from datasets import load_dataset

In [12]:
# -------------------------------
# Load the dataset and convert to Pandas DataFrame
# -------------------------------

# Load the fraud detection dataset from Hugging Face
dataset = load_dataset("CiferAI/Cifer-Fraud-Detection-Dataset-AF")

# Convert the training split of the dataset to a Pandas DataFrame for easier manipulation
df = dataset["train"].to_pandas()

# Convert columns to the best possible dtypes (e.g., int64 → Int64, object → string)
# This helps prevent potential type issues and ensures consistent data types
df = df.convert_dtypes()

In [3]:
# -------------------------------
# Explore basic information about the dataset
# -------------------------------

# Display the first 5 rows to get an overview of the data
print("First 5 rows of the dataset:")
display(df.head())

First 5 rows of the dataset:

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
9811966,147,CASH_IN,329822.99,sdv-pii-1hybr,4806431.42,5947257.03,sdv-pii-a89t7,419530.31,3697373.7,0,0
3361606,450,PAYMENT,20295.13,C1114778583,0.01,499.17,C689793442,4467189.32,1290654.24,0,0
12871380,57,CASH_OUT,32781.69,sdv-pii-suuas,143.37,20.69,sdv-pii-k2ai2,1129675.95,4979770.75,0,0
20899941,210,CASH_OUT,94808.87,C1629867471,974.7,32834.22,C350001556,526137.5,3.11,0,0
4740903,362,CASH_OUT,84063.92,C1758188565,192732.65,417339.55,M1856647425,1131265.84,4833.99,0,0

In [ ]:
import pandas as pd

df['nb_occurrences_Orig'] = df.groupby('nameOrig')['nameOrig'].transform('count')
df['nb_occurrences_Dest'] = df.groupby('nameDest')['nameOrig'].transform('count')

In [17]:
df['nb_occurrences_Dest'] = df.groupby('nameDest')['nameOrig'].transform('count')

In [19]:
df.head()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud,nb_occurrences,nb_occurrences_Dest
0,371,CASH_OUT,367336.05,sdv-pii-r8zd6,4514816.83,2108392.86,sdv-pii-q6998,1265486.06,2454140.46,0,0,1,1
1,368,TRANSFER,238.63,sdv-pii-xq6z3,430944.71,1865444.6,sdv-pii-n2ql8,107927.46,2021.16,0,0,1,1
2,141,CASH_OUT,254.93,sdv-pii-805w0,839593.53,8008353.88,sdv-pii-yo0z6,773352.22,20.79,0,0,1,1
3,191,CASH_IN,501547.39,sdv-pii-279tw,41226.4,28633.52,sdv-pii-9zlyl,6825363.55,16442078.24,0,0,1,1
4,169,TRANSFER,71832.0,sdv-pii-ksz58,248694.6,793617.86,sdv-pii-0ykbo,579313.76,829850.96,0,0,1,1

In [18]:
df['isFraud'].corr(df['nb_occurrences_Dest'])

np.float64(-0.00036559461586782485)

In [20]:
df['isFraud'].corr(df['nb_occurrences'])

np.float64(-0.00011588293760787544)

21000000

In [23]:
df["isFraud"].sum()/len(df)

np.float64(0.0013080952380952382)

In [24]:
print(df["nb_occurrences_Dest"].max())

292